### PR TITLE
chore: Add initial `PipelineUpdateRequest` class

### PR DESCRIPTION
**Pull request by danielwis**
## Describe your changes
This adds a `PostRequest` class that can be used to send HTTP POST requests, which is the first step towards fixing #28.

## Checklist before requesting review

-   [x] Feature/fix PRs should add one atomic (as small as possible) feature or
        fix
-   [x] If your PR adds a feature or fix it also needs to add or modify at least
        one test
-   [x] All code in your PR needs to have been formatted
-   [x] The merge commit title should follow our commit prefix convention of
        either "feat", "fix", "chore", "doc", or "refactor"
-   [x] The merge commit body should reference at least one issue
-   [x] The code compiles and all the tests pass

### CODE REVIEW

**Review by didrikmunther — COMMENTED** [review]
Is `PostRequest` a good name for this implementation? It certainly is a PostRequest, but the purpose of doing this request is to give GitHub an update about the status of the CI pipeline. Perhaps something like `PipelineUpdateMessage` or similar would be more appropriate?

Do we also need some way of telling GitHub exactly which step succeeded or failed?

**Comment by danielwis** [comment]
That would be a little more explanatory, yes. However, I think we should still have the `Request…` subclasses, as the “internals” still concern an HTTP request.
Re. which step failed, this could be specified in the `description` field.

**Comment by didrikmunther** [comment]
I agree we should keep the `Request...` prefix.

When building with the already existing tool, it seems to have discrete steps for every part in the pipeline. I think we will require a separate variable for exactly which step failed, or some other solution.

Screenshot 2023-02-03 at 21 36 39

**Comment by danielwis** [comment]
I could absolutely add a variable to the class, but there are no more request fields offered by the API than those already listed as member variables. It could still be useful, of course, for either the build info (P+ assignment) and/or the API call description field as mentioned.

**Review by didrikmunther — APPROVED** [review]
Alright, LGTM!

**Review by didrikmunther — APPROVED** [review]
LGTM

**Pull request merged**
